#!/bin/bash

version="1.2"
#=========================================================#
# docker database server stop
docker stop demo-app-db-$version
docker rm demo-app-db-$version

#=========================================================#
#=========================================================#
# docker web server stop
docker stop demo-app-web-$version
docker rm demo-app-web-$version

#=========================================================#
