#!/bin/bash

#=========================================================#
# demo-app version
version="1.2"

#=========================================================#
#=========================================================#
# get the current directory
current=$(realpath "$0")
current=$(dirname "$current")

#=========================================================#
#=========================================================#
opts=$(getopt -o m::n: --long main::,name: -n "script" -- "$@")
eval set -- "$opts"

file_name=$(date +'%Y-%m-%d-%H-%M-%S')

while true; do
    case "$1" in
        -m | --main)
            #=========================================================#
            # Rewrite main directory.
            docker cp demo-app-web-$version:/var/www $current/web/main
            shift
            ;;
            #=========================================================#
        -n | --name)
            if [[ -z $2 ]]; then
                echo "The argument for option '$1' is missing."
                exit 1
            fi
            #=========================================================#
            # Set the directory name.
            file_name="$2"
            shift 2
            ;;
            #=========================================================#
        --)
            #=========================================================#
            docker cp demo-app-web-$version:/var/www $current/web/.backups/$file_name
            tar -czvf $current/web/.backups/$file_name.tar.gz -C $current/web/.backups/ $file_name
            rm -rf $current/web/.backups/$file_name

            shift
            ;;
            #=========================================================#
        *)
            echo "Invalid option: $1"
            exit 1
            ;;
    esac
done
